### ISSUE TITLE
新建用户提示 "该账号暂无权限登录"

### ISSUE THREAD

**Issue by trdmm** [dcloudio/uniCloud-admin#1]
没有添加角色权限啥的

**Comment by fxy060608** [comment]
用户登录时，会根据用户的 角色 去查找其拥有的 权限 ，再根据 权限 去查找对应的 菜单
如果没有查找到菜单，则提示该账户暂无权限登录
可以通过超级管理员，调整该用户的角色或角色对应权限

**Comment by trdmm** [comment]
> 用户登录时，会根据用户的 角色 去查找其拥有的 权限 ，再根据 权限 去查找对应的 菜单
> 如果没有查找到菜单，则提示该账户暂无权限登录
> 可以通过超级管理员，调整该用户的角色或角色对应权限

不是有静态菜单的么,我还以为没权限静态菜单可用...😭😭😭
