### ISSUE TITLE
绑定云空间后uni变量无法使用

### ISSUE THREAD

**Issue by MonsterGene** [dcloudio/uniCloud-admin#7]
绑定云空间后uni变了无法使用：
![image](https://user-images.githubusercontent.com/32955859/122592264-a4978f80-d096-11eb-912e-851f8b7219c5.png)

请帮忙修复此问题，谢谢

**Comment by qiuxiaojian** [comment]
我也出现了同样的问题，直接卡在第一步，绑定空间直接打不开了

**Comment by Fasttian** [comment]
此 bug 已修复，更新最新的编辑器 [HBuilder X](https://dcloud.io/hbuilderx.html) 尝试
