### ISSUE TITLE
分页功能出错

### ISSUE THREAD

**Issue by spidergood** [dcloudio/uniCloud-admin#8]
在用户管理模块，分页组件上可以选择每页选择多少条数据，默认是显示20条，如果改变每页显示条数，表格数据刷新不会更新分页数据，一直保持默认的数据。

**Comment by spidergood** [comment]
我测试了官方的测试用户   在 用户管理模块，增加 用户数到21个，此时出现21条数据，有两页，然后选择前面的显示条数，选择魏50条，正常会更新为一页显示21条数据，页数为1，但实际 页面仍然是 每页显示20条，分页也是 显示两页，页面刷新了，但是依然是之前一样的显示。通过修改代码，把每天显示条数更改成5页，选择每天显示条数。同样不会更新表格数据和分页信息。

**Comment by spidergood** [comment]
想了个临时解决办法，在 unicloud-db.vue文件中  的 263行处插入  if (args1.size !== undefined) {
          this.paginationInternal.size = args1.size
        }，在调用 load方法的时候，

**Comment by Fasttian** [comment]
确认 bug

**Comment by Fasttian** [comment]
3.2.10 版 HBuilder X 已处理，即将发布，届时请更新
